// frontend/src/components/studio/StudioPanel.vue
<script setup lang="ts">
/**
 * StudioPanel Component
 * Educational Note: Layout-only orchestrator. Provides StudioProvider context
 * and renders collapsed/expanded views.
 *
 * The Vue equivalent of React's Context Provider pattern uses provide/inject
 * via the useStudioProvider() composable. StudioPanel calls useStudioProvider()
 * once, which provide()s the studio context to all child components.
 * Children call useStudioContext() to inject it.
 */
import { useStudioProvider } from '@/composables/useStudio'
import { ScrollArea } from '@/components/ui/scroll-area'
import StudioHeader from './StudioHeader.vue'
import StudioToolsList from './StudioToolsList.vue'
import StudioCollapsedView from './StudioCollapsedView.vue'
import StudioSignalPicker from './StudioSignalPicker.vue'
import StudioSections from './sections/StudioSections.vue'
import type { StudioSignal } from '@/lib/types/studio'

const props = defineProps<{
  projectId: string
  signals: StudioSignal[]
  isCollapsed?: boolean
  onExpand?: () => void
}>()

// Provide studio context to the entire panel subtree
useStudioProvider(props.projectId, () => props.signals)
</script>

<template>
  <!-- Collapsed icon strip -->
  <StudioCollapsedView
    v-if="props.isCollapsed"
    :on-expand="props.onExpand || (() => {})"
  />

  <!-- Expanded view -->
  <div v-else class="flex flex-col h-full">
    <StudioHeader />

    <!-- Top half: generation tool buttons -->
    <div class="flex-1 min-h-0 border-b flex flex-col">
      <StudioToolsList />
    </div>

    <!-- Bottom half: generated outputs -->
    <div class="flex-1 min-h-0 flex flex-col">
      <div class="px-3 py-2 border-b">
        <h3 class="text-xs font-semibold text-muted-foreground uppercase tracking-wide">
          Generated Content
        </h3>
      </div>
      <ScrollArea class="flex-1">
        <div class="p-3 space-y-2">
          <StudioSections />
        </div>
      </ScrollArea>
    </div>

    <!-- Signal picker dialog (renders in portal, always present) -->
    <StudioSignalPicker />
  </div>
</template>

// frontend/src/components/studio/StudioPanel.tsx
/**
 * StudioPanel Component
 * Educational Note: Layout-only orchestrator for the Studio panel.
 * All feature state is owned by individual sections via StudioContext.
 * This component only handles layout - no hooks, no props drilling.
 *
 * Architecture:
 * - StudioProvider: Shared context (projectId, signals, picker state)
 * - StudioToolsList: Generation tool buttons
 * - StudioSections: Self-contained feature sections (each owns its state)
 * - StudioSignalPicker: Modal for selecting from multiple signals
 */

import React from 'react';
import { StudioHeader } from './StudioHeader';
import { StudioToolsList } from './StudioToolsList';
import { StudioCollapsedView } from './StudioCollapsedView';
import { StudioSignalPicker } from './StudioSignalPicker';
import { StudioProvider, useStudioContext } from './StudioContext';
import { StudioSections } from './sections/StudioSections';
import { ScrollArea } from '../ui/scroll-area';
import type { StudioSignal } from './types';

interface StudioPanelProps {
  projectId: string;
  signals: StudioSignal[];
  isCollapsed?: boolean;
  onExpand?: () => void;
}

/**
 * Inner panel content - uses context
 */
const StudioPanelContent: React.FC = () => {
  const {
    pickerOpen,
    setPickerOpen,
    selectedItem,
    selectedSignals,
    triggerGeneration,
    getItemTitle,
    getItemIcon,
  } = useStudioContext();

  return (
    <div className="flex flex-col h-full" data-tour="studio-panel">
      <StudioHeader />

      {/* TOP HALF: Generation Tools */}
      <div className="flex-1 min-h-0 border-b flex flex-col">
        <StudioToolsList />
      </div>

      {/* BOTTOM HALF: Generated Outputs */}
      <div className="flex-1 min-h-0 flex flex-col">
        <div className="px-3 py-2 border-b">
          <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">
            Generated Content
          </h3>
        </div>

        <ScrollArea className="flex-1">
          <div className="p-3 space-y-2">
            {/* All sections render here - each manages its own state */}
            <StudioSections />
          </div>
        </ScrollArea>
      </div>

      {/* Signal Picker Dialog */}
      <StudioSignalPicker
        open={pickerOpen}
        onOpenChange={setPickerOpen}
        selectedItem={selectedItem}
        selectedSignals={selectedSignals}
        onSelectSignal={triggerGeneration}
        getItemTitle={getItemTitle}
        getItemIcon={getItemIcon}
      />
    </div>
  );
};

/**
 * Main StudioPanel - provides context and handles collapsed state
 */
export const StudioPanel: React.FC<StudioPanelProps> = ({
  projectId,
  signals,
  isCollapsed,
  onExpand,
}) => {
  // Collapsed view doesn't need the full context
  if (isCollapsed) {
    return (
      <StudioProvider projectId={projectId} signals={signals}>
        <CollapsedViewWrapper onExpand={onExpand!} />
      </StudioProvider>
    );
  }

  return (
    <StudioProvider projectId={projectId} signals={signals}>
      <StudioPanelContent />
    </StudioProvider>
  );
};

/**
 * Wrapper for collapsed view that uses context
 */
const CollapsedViewWrapper: React.FC<{ onExpand: () => void }> = ({ onExpand }) => {
  const { signals, handleGenerate } = useStudioContext();

  return (
    <StudioCollapsedView
      signals={signals}
      onExpand={onExpand}
      onGenerate={handleGenerate}
    />
  );
};
