// frontend/src/components/chat/ChatPanel.tsx
/**
 * ChatPanel Component
 * Educational Note: Main orchestrator for the chat interface.
 * Composes smaller components (ChatHeader, ChatMessages, ChatInput, etc.)
 * and manages chat state and API interactions.
 */

import React, { useState, useEffect, useCallback, useRef } from 'react';
import { Sparkle } from '@phosphor-icons/react';
import axios from 'axios';
import { Skeleton } from '../ui/skeleton';
import { chatsAPI } from '@/lib/api/chats';
import type { Chat, ChatMetadata, ChatSyncPayload, StudioSignal } from '@/lib/api/chats';
import type { CostTracking } from '@/lib/api/projects';
import { usersAPI, type UserUsage } from '@/lib/api/settings';
import { sourcesAPI, type Source } from '@/lib/api/sources';
import { ToastContainer } from '../ui/toast';
import { useToast } from '../ui/use-toast';
import { useVoiceRecording } from '../hooks/useVoiceRecording';
import { ChatHeader } from './ChatHeader';
import { ChatMessages } from './ChatMessages';
import { ChatInput } from './ChatInput';
import { ChatList } from './ChatList';
import { ChatEmptyState } from './ChatEmptyState';
import { RawMessageView } from './RawMessageView';
import { exportChatAsPdf } from '@/lib/exportChatPdf';
import { createLogger } from '@/lib/logger';
import { API_BASE_URL } from '@/lib/api/client';

const log = createLogger('chat-panel');

interface ChatPanelProps {
  projectId: string;
  projectName: string;
  sourcesVersion?: number;
  onCostsChange?: () => void; // Called after message sent to trigger cost refresh
  onSignalsChange?: (signals: StudioSignal[]) => void; // Called when studio signals change
  selectedSourceIds: string[]; // Per-chat source selection from parent
  onActiveChatChange: (chatId: string | null, selectedSourceIds: string[]) => void; // Notify parent of chat change
  sendingChatIds: Set<string>; // All chats currently processing (owned by parent)
  onAddSendingChat: (chatId: string, chatName?: string) => void;
  onRemoveSendingChat: (chatId: string) => void;
  openChatId?: string | null; // When set, ChatPanel switches to this chat
}

export const ChatPanel: React.FC<ChatPanelProps> = ({
  projectId,
  projectName,
  sourcesVersion,
  onCostsChange,
  onSignalsChange,
  selectedSourceIds,
  onActiveChatChange,
  sendingChatIds,
  onAddSendingChat,
  onRemoveSendingChat,
  openChatId,
}) => {
  const { toasts, dismissToast, success, error, errorWithLogs } = useToast();

  // Chat state
  const [message, setMessage] = useState('');
  const [activeChat, setActiveChat] = useState<Chat | null>(null);
  const [showChatList, setShowChatList] = useState(false);
  const [allChats, setAllChats] = useState<ChatMetadata[]>([]);
  const [loading, setLoading] = useState(true);
  // Derive sending state for current chat from parent-owned Set
  const sending = activeChat ? sendingChatIds.has(activeChat.id) : false;
  const [exportingChat, setExportingChat] = useState(false);
  const [rawMode, setRawMode] = useState(false);
  const [streamingAssistantContent, setStreamingAssistantContent] = useState('');
  const [titleSyncPollKey, setTitleSyncPollKey] = useState(0);
  // AbortController for cancelling in-flight chat requests
  const abortControllerRef = useRef<AbortController | null>(null);
  const canonicalUserMessageReceivedRef = useRef(false);
  const assistantDeltaReceivedRef = useRef(false);
  const pendingTitleSyncRef = useRef<{ chatId: string; hasSeenNamingTask: boolean } | null>(null);

  // Sources state for header display
  const [sources, setSources] = useState<Source[]>([]);

  // Per-chat cost tracking (shown in ChatHeader)
  const [chatCosts, setChatCosts] = useState<CostTracking | null>(null);

  // User spending limit usage (compact progress bar in ChatHeader)
  const [userUsage, setUserUsage] = useState<UserUsage | null>(null);

  // Active sources count derived from per-chat selection
  const activeSources = selectedSourceIds.length;

  // Voice recording hook
  const {
    isRecording,
    partialTranscript,
    transcriptionConfigured,
    startRecording,
    stopRecording,
  } = useVoiceRecording({
    onError: error,
    onTranscriptCommit: useCallback((text: string) => {
      // Append committed text to message
      setMessage((prev) => {
        if (prev && !prev.endsWith(' ')) {
          return prev + ' ' + text;
        }
        return prev + text;
      });
    }, []),
  });

  /**
   * Load sources for the project (for header display)
   */
  const loadSources = async () => {
    try {
      const data = await sourcesAPI.listSources(projectId);
      setSources(data);
    } catch (err) {
      log.error({ err }, 'failed to load sources');
    }
  };

  /**
   * Load full chat data including all messages
   */
  const loadFullChat = async (chatId: string) => {
    try {
      const chat = await chatsAPI.getChat(projectId, chatId);
      setActiveChat(chat);
      // Notify parent of per-chat source selection
      onActiveChatChange(chat.id, chat.selected_source_ids ?? []);
    } catch (err) {
      log.error({ err }, 'failed to load chat');
      errorWithLogs('Failed to load chat');
    }
  };

  /**
   * Load all chats for the project
   */
  const loadChats = async () => {
    try {
      setLoading(true);
      const chats = await chatsAPI.listChats(projectId);
      setAllChats(chats);

      // If we have chats and no active chat, load the first one
      if (chats.length > 0 && !activeChat) {
        await loadFullChat(chats[0].id);
      }
    } catch (err) {
      log.error({ err }, 'failed to load chats');
      errorWithLogs('Failed to load chats');
    } finally {
      setLoading(false);
    }
  };

  /**
   * Load all chats and sources when component mounts or projectId changes
   */
  useEffect(() => {
    loadChats();
    loadSources();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [projectId]);

  // Switch to a specific chat when parent requests it (e.g. from ActiveTasksBar "Open" button)
  useEffect(() => {
    if (openChatId && openChatId !== activeChat?.id) {
      loadFullChat(openChatId);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [openChatId]);

  /**
   * Refetch sources when sourcesVersion changes
   * Educational Note: This triggers when SourcesPanel notifies us that sources
   * have changed (toggle active, delete, processing complete, etc.)
   */
  useEffect(() => {
    if (sourcesVersion !== undefined && sourcesVersion > 0) {
      loadSources();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sourcesVersion]);

  /**
   * Notify parent when studio signals change
   * Educational Note: Signals are stored in the chat and loaded/updated
   * when chat is loaded or after messages are sent.
   */
  useEffect(() => {
    if (activeChat) {
      onSignalsChange?.(activeChat.studio_signals || []);
    } else {
      onSignalsChange?.([]);
    }
  }, [activeChat, onSignalsChange]);

  /**
   * Load per-chat cost/token breakdown whenever the active chat changes.
   * Refreshed again after each message via `loadChatCosts()` in the send flow.
   */
  const loadChatCosts = useCallback(async (chatId: string) => {
    try {
      const costs = await chatsAPI.getCosts(projectId, chatId);
      setChatCosts(costs);
    } catch (err) {
      log.error({ err }, 'failed to load chat costs');
    }
  }, [projectId]);

  const loadUserUsage = useCallback(async () => {
    try {
      const data = await usersAPI.getMyUsage();
      setUserUsage(data);
    } catch {
      // Silent — usage is not critical
    }
  }, []);

  const applyChatSync = useCallback((sync?: ChatSyncPayload | null): boolean => {
    if (!sync?.chat) {
      return false;
    }

    const syncedChat = sync.chat;

    setAllChats((prev) => {
      const existing = prev.find((chat) => chat.id === syncedChat.id);
      const nextChat: ChatMetadata = {
        id: syncedChat.id,
        title: syncedChat.title,
        created_at: syncedChat.created_at,
        updated_at: syncedChat.updated_at,
        message_count: syncedChat.message_count,
      };

      if (existing &&
          existing.title === nextChat.title &&
          existing.updated_at === nextChat.updated_at &&
          existing.message_count === nextChat.message_count) {
        return prev;
      }

      return [nextChat, ...prev.filter((chat) => chat.id !== syncedChat.id)];
    });

    setActiveChat((prev) => {
      if (!prev || prev.id !== syncedChat.id) {
        return prev;
      }

      return {
        ...prev,
        title: syncedChat.title,
        updated_at: syncedChat.updated_at,
        selected_source_ids: syncedChat.selected_source_ids,
        studio_signals: sync.studio_signals ?? prev.studio_signals,
      };
    });

    if (sync.chat_costs) {
      setChatCosts(sync.chat_costs);
    }

    if (sync.user_usage) {
      setUserUsage(sync.user_usage);
    }

    onCostsChange?.();
    return true;
  }, [onCostsChange]);

  const reconcileChatMetadata = useCallback(async (chatId: string) => {
    try {
      const [chat] = await Promise.all([
        chatsAPI.getChat(projectId, chatId),
        loadChatCosts(chatId),
        loadUserUsage(),
      ]);

      setAllChats((prev) => {
        const existing = prev.find((item) => item.id === chat.id);
        const nextChat: ChatMetadata = existing
          ? {
              ...existing,
              title: chat.title,
              updated_at: chat.updated_at,
              message_count: chat.messages.length,
            }
          : {
              id: chat.id,
              title: chat.title,
              created_at: chat.created_at,
              updated_at: chat.updated_at,
              message_count: chat.messages.length,
            };

        return [nextChat, ...prev.filter((item) => item.id !== chat.id)];
      });

      setActiveChat((prev) => {
        if (!prev || prev.id !== chat.id) {
          return prev;
        }

        return {
          ...prev,
          title: chat.title,
          updated_at: chat.updated_at,
          selected_source_ids: chat.selected_source_ids,
          studio_signals: chat.studio_signals || prev.studio_signals,
        };
      });
    } catch (err) {
      log.error({ err, chatId }, 'failed to reconcile chat metadata');
    }
  }, [loadChatCosts, loadUserUsage, projectId]);

  useEffect(() => {
    if (activeChat?.id) {
      loadChatCosts(activeChat.id);
    } else {
      setChatCosts(null);
    }
  }, [activeChat?.id, loadChatCosts]);

  // Load user usage on mount
  useEffect(() => {
    loadUserUsage();
  }, [loadUserUsage]);

  useEffect(() => {
    if (!pendingTitleSyncRef.current) {
      return undefined;
    }

    const pending = pendingTitleSyncRef.current;
    const startedAt = Date.now();
    // Ceiling so a fast-completing name task that we never observe in
    // /active-tasks still triggers a reconcile. Haiku often returns in
    // 1-3s, so anything past 8s means either we missed the window or the
    // task failed silently — either way, pull fresh metadata.
    const MAX_WAIT_MS = 8000;
    let cancelled = false;

    const finishAndReconcile = async () => {
      pendingTitleSyncRef.current = null;
      await reconcileChatMetadata(pending.chatId);
      if (!cancelled) {
        setTitleSyncPollKey((prev) => prev + 1);
      }
    };

    const checkForCompletedNaming = async () => {
      if (cancelled || pendingTitleSyncRef.current !== pending) {
        return;
      }

      const elapsed = Date.now() - startedAt;

      try {
        const response = await axios.get(`${API_BASE_URL}/projects/${projectId}/active-tasks`);
        if (cancelled || pendingTitleSyncRef.current !== pending) {
          return;
        }

        const namingTask = response.data.success
          ? (response.data.tasks || []).find((task: {
              type?: string;
              target_id?: string;
              target_type?: string;
              task_type?: string;
            }) => (
              task.type === 'background' &&
              task.target_type === 'chat' &&
              task.target_id === pending.chatId &&
              task.task_type === 'chat_naming'
            ))
          : undefined;

        if (namingTask) {
          pending.hasSeenNamingTask = true;
          return;
        }

        if (pending.hasSeenNamingTask || elapsed >= MAX_WAIT_MS) {
          await finishAndReconcile();
        }
      } catch {
        if (elapsed >= MAX_WAIT_MS && !cancelled && pendingTitleSyncRef.current === pending) {
          await finishAndReconcile();
        }
      }
    };

    void checkForCompletedNaming();
    const intervalId = window.setInterval(() => {
      void checkForCompletedNaming();
    }, 2000);

    return () => {
      cancelled = true;
      window.clearInterval(intervalId);
    };
  }, [projectId, reconcileChatMetadata, titleSyncPollKey]);

  /**
   * Send a message and get AI response
   * Educational Note: We add the user message optimistically to the UI
   * before the API call, so users see their message immediately.
   */
  const handleSend = async () => {
    if (!message.trim() || !activeChat || sending) return;

    const userMessage = message.trim();
    const currentChat = activeChat;
    const sendingChatId = currentChat.id;
    const controller = new AbortController();
    abortControllerRef.current = controller;
    canonicalUserMessageReceivedRef.current = false;
    assistantDeltaReceivedRef.current = false;
    setMessage('');
    setRawMode(false);
    setStreamingAssistantContent('');
    onAddSendingChat(sendingChatId, activeChat.title);

    // Optimistically add user message to UI immediately
    const tempUserMessage = {
      id: `temp-${Date.now()}`,
      role: 'user' as const,
      content: userMessage,
      timestamp: new Date().toISOString(),
    };

    setActiveChat((prev) => {
      if (!prev) return null;
      return {
        ...prev,
        messages: [...prev.messages, tempUserMessage],
      };
    });

    const replaceTempWithCanonicalUser = (canonicalUserMessage: Chat['messages'][number]) => {
      // Some SSE producers occasionally emit a `user_message` event with a
      // missing/null payload during reconnects. Bail out instead of poisoning
      // activeChat.messages with `undefined`, which crashes the renderer
      // (`Cannot read properties of undefined (reading 'id')`).
      if (!canonicalUserMessage?.id) return;
      canonicalUserMessageReceivedRef.current = true;
      setActiveChat((prev) => {
        if (!prev) return null;
        const nextMessages = prev.messages.map((msg) =>
          msg.id === tempUserMessage.id ? canonicalUserMessage : msg
        );
        const alreadyPresent = nextMessages.some((msg) => msg.id === canonicalUserMessage.id);
        return {
          ...prev,
          messages: alreadyPresent ? nextMessages : [...nextMessages.filter((msg) => msg.id !== tempUserMessage.id), canonicalUserMessage],
        };
      });
    };

    const appendAssistantMessage = (assistantMessage: Chat['messages'][number]) => {
      // Same defensive guard as replaceTempWithCanonicalUser. See note there.
      if (!assistantMessage?.id) {
        log.warn('appendAssistantMessage called with empty payload — ignoring');
        setStreamingAssistantContent('');
        return;
      }
      // Append the final message first, THEN clear streaming content in the
      // same React batch. This prevents a flash where neither the streaming
      // bubble nor the final message is visible.
      setActiveChat((prev) => {
        if (!prev) return null;
        const messagesWithoutTemp = prev.messages.filter((m) => m.id !== tempUserMessage.id);
        if (messagesWithoutTemp.some((msg) => msg.id === assistantMessage.id)) {
          return { ...prev, messages: messagesWithoutTemp, updated_at: new Date().toISOString() };
        }
        return {
          ...prev,
          messages: [...messagesWithoutTemp, assistantMessage],
          updated_at: new Date().toISOString(),
        };
      });
      setStreamingAssistantContent('');
    };

    const applyFallbackResponse = (result: {
      user_message: Chat['messages'][number];
      assistant_message: Chat['messages'][number];
      sync?: ChatSyncPayload | null;
    }) => {
      canonicalUserMessageReceivedRef.current = true;
      setStreamingAssistantContent('');
      setActiveChat((prev) => {
        if (!prev) return null;
        const messagesWithoutTemp = prev.messages.filter((m) => m.id !== tempUserMessage.id);
        // Filter out anything missing an `id` so a malformed REST fallback
        // payload doesn't crash the renderer downstream.
        const incoming = [result.user_message, result.assistant_message].filter(
          (m): m is Chat['messages'][number] => Boolean(m?.id),
        );
        return {
          ...prev,
          messages: [...messagesWithoutTemp, ...incoming],
          updated_at: new Date().toISOString(),
        };
      });
    };

    const shouldWatchForTitleUpdate = currentChat.messages.length === 0;
    if (shouldWatchForTitleUpdate) {
      pendingTitleSyncRef.current = {
        chatId: currentChat.id,
        hasSeenNamingTask: false,
      };
      setTitleSyncPollKey((prev) => prev + 1);
    }

    let receivedTerminalSync = false;

    try {
      const streamResult = await chatsAPI.streamMessage(
        projectId,
        currentChat.id,
        userMessage,
        {
          onUserMessage: replaceTempWithCanonicalUser,
          onAssistantDelta: (delta) => {
            assistantDeltaReceivedRef.current = true;
            setStreamingAssistantContent((prev) => prev + delta);
          },
          onAssistantDone: (payload) => {
            appendAssistantMessage(payload.assistant_message);
            receivedTerminalSync = applyChatSync(payload.sync);
          },
          onErrorEvent: (payload) => {
            setStreamingAssistantContent('');
            if (payload.assistant_message) {
              appendAssistantMessage(payload.assistant_message);
            }
            receivedTerminalSync = applyChatSync(payload.sync);
          },
        },
        controller.signal
      );

      if (streamResult.terminalEvent) {
        if (!receivedTerminalSync && streamResult.terminalSync) {
          receivedTerminalSync = applyChatSync(streamResult.terminalSync);
        }
        if (!receivedTerminalSync) {
          onCostsChange?.();
          await reconcileChatMetadata(currentChat.id);
        }
      } else {
        // Stream closed cleanly but neither `assistant_done` nor `error`
        // arrived. The most common cause is an upstream proxy (frontend
        // nginx, Coolify Traefik) FIN'ing the connection during a long
        // tool-use gap — the backend has already persisted the assistant
        // message via main_chat_service, so a refetch surfaces it without
        // re-running the model. Without this branch the UI stuck on the
        // Reading Beat until the user manually refreshed (#item-still-not-
        // working repro from prod logs showed 407s / 523s / 658s streams).
        log.warn(
          {
            chatId: currentChat.id,
            hadUserMessage: streamResult.hadUserMessage,
            hadAssistantDelta: streamResult.hadAssistantDelta,
          },
          'stream ended without terminal event — recovering from server',
        );
        setStreamingAssistantContent('');
        try {
          await loadFullChat(currentChat.id);
          onCostsChange?.();
          await loadUserUsage();
        } catch (recoveryErr) {
          log.error({ err: recoveryErr }, 'recovery refetch failed');
          errorWithLogs(
            'Connection dropped before the response arrived. Refresh to load it.',
          );
        }
      }
    } catch (err) {
      // Don't show error toast if user intentionally stopped
      const isAborted = err instanceof Error && (err.name === 'CanceledError' || err.name === 'AbortError');
      if (isAborted) {
        log.info('Chat request stopped by user');
      } else {
        const shouldFallback = !canonicalUserMessageReceivedRef.current && !assistantDeltaReceivedRef.current;

        if (shouldFallback) {
          try {
            const fallbackResult = await chatsAPI.sendMessage(projectId, currentChat.id, userMessage);
            applyFallbackResponse(fallbackResult);
            if (!applyChatSync(fallbackResult.sync)) {
              onCostsChange?.();
              await reconcileChatMetadata(currentChat.id);
            }
          } catch (fallbackError) {
            log.error({ err: fallbackError }, 'failed to send message via fallback');
            errorWithLogs('Failed to send message');
          }
        } else {
          // Stream errored mid-flight after delivering partial events
          // (canonical user_message and/or assistant_delta). Re-sending
          // via the REST fallback would duplicate the user's message —
          // recover by re-fetching the chat instead. The backend's
          // exception handler in main_chat_service already persists an
          // error-marked assistant message before the SSE error event,
          // so the refetch should surface either the partial response
          // or a recorded failure the user can retry from.
          log.warn({ err }, 'stream errored after partial events — recovering from server');
          try {
            await loadFullChat(currentChat.id);
            onCostsChange?.();
            await loadUserUsage();
          } catch (recoveryErr) {
            log.error({ err: recoveryErr }, 'recovery refetch failed');
            errorWithLogs('Failed to send message');
          }
        }
      }
      setStreamingAssistantContent('');
      if (!canonicalUserMessageReceivedRef.current) {
        setActiveChat((prev) => {
          if (!prev) return null;
          return {
            ...prev,
            messages: prev.messages.filter((m) => m.id !== tempUserMessage.id),
          };
        });
      }
    } finally {
      onRemoveSendingChat(sendingChatId);
      abortControllerRef.current = null;
    }
  };

  /**
   * Stop the current in-flight chat request
   */
  const handleStop = () => {
    if (abortControllerRef.current) {
      abortControllerRef.current.abort();
      abortControllerRef.current = null;
    }
    setStreamingAssistantContent('');
  };

  /**
   * Create a new chat
   */
  const handleNewChat = async () => {
    try {
      const newChat = await chatsAPI.createChat(projectId, 'New Chat');
      setAllChats((prev) => [newChat, ...prev]);
      await loadFullChat(newChat.id);
      // New chats start with no sources selected (loadFullChat will call onActiveChatChange)
      setShowChatList(false);
      success('New chat created');
    } catch (err) {
      log.error({ err }, 'failed to create chat');
      error('Failed to create chat');
    }
  };

  /**
   * Select a chat from the list
   */
  const handleSelectChat = async (chatId: string) => {
    await loadFullChat(chatId);
    setShowChatList(false);
  };

  /**
   * Delete a chat
   */
  const handleDeleteChat = async (chatId: string) => {
    try {
      await chatsAPI.deleteChat(projectId, chatId);
      const remainingChats = allChats.filter((chat) => chat.id !== chatId);
      setAllChats(remainingChats);

      // If the deleted chat was active, clear it and reset source selection
      if (activeChat?.id === chatId) {
        setActiveChat(null);
        onActiveChatChange(null, []);

        if (remainingChats.length > 0) {
          await loadFullChat(remainingChats[0].id);
        }
      }
      success('Chat deleted');
    } catch (err) {
      log.error({ err }, 'failed to delete chat');
      error('Failed to delete chat');
    }
  };

  /**
   * Rename a chat
   */
  const handleRenameChat = async (chatId: string, newTitle: string) => {
    try {
      const updatedChat = await chatsAPI.updateChat(projectId, chatId, newTitle);
      setAllChats((prev) => prev.map((chat) => (
        chat.id === chatId
          ? {
              ...chat,
              title: updatedChat.title,
              updated_at: updatedChat.updated_at,
              message_count: updatedChat.message_count,
            }
          : chat
      )));

      // Update active chat if it was renamed
      if (activeChat?.id === chatId) {
        setActiveChat(prev => prev ? { ...prev, title: updatedChat.title } : null);
      }

      success('Chat renamed');
    } catch (err) {
      log.error({ err }, 'failed to rename chat');
      error('Failed to rename chat');
    }
  };

  /**
   * Toggle recording on/off
   */
  const handleMicClick = () => {
    if (isRecording) {
      stopRecording();
    } else {
      startRecording();
    }
  };

  /**
   * Export the active chat as a PDF file
   */
  const handleExportChat = useCallback(async () => {
    if (!activeChat) return;
    setExportingChat(true);
    try {
      await exportChatAsPdf({ chat: activeChat, projectId, projectName });
      success('Chat exported as PDF');
    } catch (err) {
      log.error({ err }, 'Failed to export chat as PDF');
      error('Failed to export chat');
    } finally {
      setExportingChat(false);
    }
  }, [activeChat, projectId, projectName, success, error]);

  // Loading state
  if (loading) {
    return (
      <div className="flex flex-col h-full bg-card">
        <div className="border-b px-4 py-3">
          <div className="flex items-center gap-2">
            <Sparkle size={20} className="text-primary" />
            <h2 className="font-semibold">Chat</h2>
          </div>
          <p className="text-xs text-muted-foreground mt-1">
            Ask questions about your sources or request analysis
          </p>
        </div>
        <div className="flex-1 p-6 space-y-4">
          {/* Skeleton message bubbles mimicking a chat conversation */}
          <div className="flex justify-end">
            <Skeleton className="h-10 w-2/3 rounded-2xl" />
          </div>
          <div className="flex justify-start gap-3">
            <Skeleton className="h-8 w-8 rounded-full flex-shrink-0" />
            <div className="space-y-2 flex-1">
              <Skeleton className="h-4 w-full" />
              <Skeleton className="h-4 w-5/6" />
              <Skeleton className="h-4 w-3/4" />
            </div>
          </div>
          <div className="flex justify-end">
            <Skeleton className="h-8 w-1/2 rounded-2xl" />
          </div>
          <div className="flex justify-start gap-3">
            <Skeleton className="h-8 w-8 rounded-full flex-shrink-0" />
            <div className="space-y-2 flex-1">
              <Skeleton className="h-4 w-full" />
              <Skeleton className="h-4 w-4/5" />
            </div>
          </div>
        </div>
        <ToastContainer toasts={toasts} onDismiss={dismissToast} />
      </div>
    );
  }

  // Empty state - no chats exist
  if (allChats.length === 0 && !activeChat) {
    return (
      <>
        <ChatEmptyState projectName={projectName} onNewChat={handleNewChat} />
        <ToastContainer toasts={toasts} onDismiss={dismissToast} />
      </>
    );
  }

  // Chat list view
  if (showChatList) {
    return (
      <>
        <ChatList
          chats={allChats}
          sendingChatIds={sendingChatIds}
          onSelectChat={handleSelectChat}
          onDeleteChat={handleDeleteChat}
          onRenameChat={handleRenameChat}
          onNewChat={handleNewChat}
        />
        <ToastContainer toasts={toasts} onDismiss={dismissToast} />
      </>
    );
  }

  // Active chat view
  return (
    <div className="flex flex-col h-full min-h-0 min-w-0 w-full bg-card overflow-hidden">
      <ChatHeader
        activeChat={activeChat}
        allChats={allChats}
        activeSources={activeSources}
        totalSources={sources.length}
        chatCosts={chatCosts}
        userUsage={userUsage}
        onSelectChat={handleSelectChat}
        onNewChat={handleNewChat}
        onShowChatList={() => setShowChatList(true)}
        onExportChat={handleExportChat}
        exportingChat={exportingChat}
      />

      {rawMode && activeChat ? (
        <RawMessageView projectId={projectId} chatId={activeChat.id} />
      ) : (
        <ChatMessages
          messages={activeChat?.messages || []}
          sending={sending}
          projectId={projectId}
          streamingAssistantContent={streamingAssistantContent}
        />
      )}

      <ChatInput
        message={message}
        partialTranscript={partialTranscript}
        isRecording={isRecording}
        sending={sending}
        transcriptionConfigured={transcriptionConfigured}
        rawMode={rawMode}
        onMessageChange={setMessage}
        onSend={handleSend}
        onStop={handleStop}
        onMicClick={handleMicClick}
        onToggleRawMode={() => setRawMode((prev) => !prev)}
      />

      <ToastContainer toasts={toasts} onDismiss={dismissToast} />
    </div>
  );
};

// frontend/src/components/chat/ChatPanel.vue
<script setup lang="ts">
/**
 * ChatPanel Component
 * Educational Note: Main orchestrator for the chat interface.
 * - `onMounted` + `watch` replace React's useEffect
 * - `useVoiceRecording` composable replaces the React hook
 * - `toast` from vue-sonner replaces the custom useToast hook
 */
import { ref, watch, onMounted } from 'vue'
import { toast } from 'vue-sonner'
import { PhSparkle } from '@phosphor-icons/vue'
import { Skeleton } from '@/components/ui/skeleton'
import { chatsAPI, type Chat, type ChatMetadata } from '@/lib/api/chats'
import type { StudioSignal } from '@/lib/types/studio'
import { sourcesAPI, type Source } from '@/lib/api/sources'
import { useVoiceRecording } from '@/composables/useVoiceRecording'
import { exportChatAsMarkdown } from '@/lib/exportChatMarkdown'
import { createLogger } from '@/lib/logger'
import ChatHeader from './ChatHeader.vue'
import ChatMessages from './ChatMessages.vue'
import ChatInput from './ChatInput.vue'
import ChatList from './ChatList.vue'
import ChatEmptyState from './ChatEmptyState.vue'

const log = createLogger('chat-panel')

const props = defineProps<{
  projectId: string
  projectName: string
  sourcesVersion?: number
  selectedSourceIds: string[]
}>()

const emit = defineEmits<{
  costsChange: []
  signalsChange: [signals: StudioSignal[]]
  activeChatChange: [chatId: string | null, sourceIds: string[]]
}>()

// ── State ─────────────────────────────────────────────────────────────────────
const message = ref('')
const activeChat = ref<Chat | null>(null)
const showChatList = ref(false)
const allChats = ref<ChatMetadata[]>([])
const loading = ref(true)
const sending = ref(false)
const exportingChat = ref(false)
const sources = ref<Source[]>([])

const activeSources = () => props.selectedSourceIds.length

// ── Voice recording ───────────────────────────────────────────────────────────
const { isRecording, partialTranscript, transcriptionConfigured, startRecording, stopRecording } =
  useVoiceRecording({
    onError: (msg: string) => toast.error(msg),
    onTranscriptCommit: (text: string) => {
      const prev = message.value
      message.value = prev + (prev && !prev.endsWith(' ') ? ' ' : '') + text
    },
  })

// ── Data loading ──────────────────────────────────────────────────────────────
async function loadSources() {
  try {
    sources.value = await sourcesAPI.listSources(props.projectId)
  } catch (err) {
    log.error({ err }, 'failed to load sources')
  }
}

async function loadFullChat(chatId: string) {
  try {
    const chat = await chatsAPI.getChat(props.projectId, chatId)
    activeChat.value = chat
    emit('activeChatChange', chat.id, chat.selected_source_ids ?? [])
  } catch (err) {
    log.error({ err }, 'failed to load chat')
    toast.error('Failed to load chat')
  }
}

async function loadChats() {
  try {
    loading.value = true
    const chats = await chatsAPI.listChats(props.projectId)
    allChats.value = chats
    if (chats.length > 0 && !activeChat.value) {
      await loadFullChat(chats[0].id)
    }
  } catch (err) {
    log.error({ err }, 'failed to load chats')
    toast.error('Failed to load chats')
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  loadChats()
  loadSources()
})

watch(() => props.sourcesVersion, (v) => {
  if (v && v > 0) loadSources()
})

// Propagate studio signals to parent when activeChat changes
watch(activeChat, (chat) => {
  emit('signalsChange', chat?.studio_signals || [])
})

// ── Send message ──────────────────────────────────────────────────────────────
async function handleSend() {
  if (!message.value.trim() || !activeChat.value || sending.value) return

  const userMessage = message.value.trim()
  message.value = ''
  sending.value = true

  // Optimistic: add user message immediately
  const tempId = `temp-${Date.now()}`
  const tempMsg = { id: tempId, role: 'user' as const, content: userMessage, timestamp: new Date().toISOString() }
  activeChat.value = { ...activeChat.value, messages: [...activeChat.value.messages, tempMsg] }

  const chatId = activeChat.value.id

  try {
    const result = await chatsAPI.sendMessage(props.projectId, chatId, userMessage)

    // Replace temp message with real messages
    if (activeChat.value?.id === chatId) {
      activeChat.value = {
        ...activeChat.value,
        messages: [
          ...activeChat.value.messages.filter(m => m.id !== tempId),
          result.user_message,
          result.assistant_message,
        ],
        updated_at: new Date().toISOString(),
      }
    }

    await loadChats()
    emit('costsChange')

    // Quick fetch for signals (1s)
    setTimeout(async () => {
      try {
        const updated = await chatsAPI.getChat(props.projectId, chatId)
        if (activeChat.value?.id === chatId)
          activeChat.value = { ...activeChat.value, studio_signals: updated.studio_signals || [] }
      } catch { /* non-critical */ }
    }, 1000)

    // Delayed fetch for title (4s)
    setTimeout(async () => {
      try {
        const updated = await chatsAPI.getChat(props.projectId, chatId)
        if (activeChat.value?.id === chatId)
          activeChat.value = { ...activeChat.value, title: updated.title, studio_signals: updated.studio_signals || [] }
        allChats.value = allChats.value.map(c => c.id === chatId ? { ...c, title: updated.title } : c)
      } catch { /* non-critical */ }
    }, 4000)
  } catch (err) {
    log.error({ err }, 'failed to send message')
    toast.error('Failed to send message')
    if (activeChat.value)
      activeChat.value = { ...activeChat.value, messages: activeChat.value.messages.filter(m => m.id !== tempId) }
  } finally {
    sending.value = false
  }
}

// ── Chat management ───────────────────────────────────────────────────────────
async function handleNewChat() {
  try {
    const newChat = await chatsAPI.createChat(props.projectId, 'New Chat')
    await loadChats()
    await loadFullChat(newChat.id)
    showChatList.value = false
    toast.success('New chat created')
  } catch (err) {
    log.error({ err }, 'failed to create chat')
    toast.error('Failed to create chat')
  }
}

async function handleSelectChat(chatId: string) {
  await loadFullChat(chatId)
  showChatList.value = false
}

async function handleDeleteChat(chatId: string) {
  try {
    await chatsAPI.deleteChat(props.projectId, chatId)
    if (activeChat.value?.id === chatId) {
      activeChat.value = null
      emit('activeChatChange', null, [])
    }
    await loadChats()
    toast.success('Chat deleted')
  } catch (err) {
    log.error({ err }, 'failed to delete chat')
    toast.error('Failed to delete chat')
  }
}

async function handleRenameChat(chatId: string, newTitle: string) {
  try {
    await chatsAPI.updateChat(props.projectId, chatId, newTitle)
    await loadChats()
    if (activeChat.value?.id === chatId)
      activeChat.value = { ...activeChat.value, title: newTitle }
    toast.success('Chat renamed')
  } catch (err) {
    log.error({ err }, 'failed to rename chat')
    toast.error('Failed to rename chat')
  }
}

async function handleExportChat() {
  if (!activeChat.value) return
  exportingChat.value = true
  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    await exportChatAsMarkdown({ chat: activeChat.value as any, projectId: props.projectId, projectName: props.projectName })
    toast.success('Chat exported as Markdown')
  } catch (err) {
    log.error({ err }, 'failed to export chat')
    toast.error('Failed to export chat')
  } finally {
    exportingChat.value = false
  }
}

function handleMicClick() {
  if (isRecording.value) stopRecording()
  else startRecording()
}
</script>

<template>
  <!-- Loading skeleton -->
  <div v-if="loading" class="flex flex-col h-full bg-card">
    <div class="border-b px-4 py-3">
      <div class="flex items-center gap-2">
        <PhSparkle :size="20" class="text-primary" />
        <h2 class="font-semibold">Chat</h2>
      </div>
      <p class="text-xs text-muted-foreground mt-1">Ask questions about your sources or request analysis</p>
    </div>
    <div class="flex-1 p-6 space-y-4">
      <div class="flex justify-end"><Skeleton class="h-10 w-2/3 rounded-2xl" /></div>
      <div class="flex justify-start gap-3">
        <Skeleton class="h-8 w-8 rounded-full flex-shrink-0" />
        <div class="space-y-2 flex-1">
          <Skeleton class="h-4 w-full" />
          <Skeleton class="h-4 w-5/6" />
          <Skeleton class="h-4 w-3/4" />
        </div>
      </div>
      <div class="flex justify-end"><Skeleton class="h-8 w-1/2 rounded-2xl" /></div>
    </div>
  </div>

  <!-- Empty state -->
  <ChatEmptyState
    v-else-if="allChats.length === 0 && !activeChat"
    :project-name="props.projectName"
    @new-chat="handleNewChat"
  />

  <!-- Chat list -->
  <ChatList
    v-else-if="showChatList"
    :chats="allChats"
    @select-chat="handleSelectChat"
    @delete-chat="handleDeleteChat"
    @rename-chat="(id, title) => handleRenameChat(id, title)"
    @new-chat="handleNewChat"
  />

  <!-- Active chat -->
  <div v-else class="flex flex-col h-full min-h-0 min-w-0 w-full bg-card overflow-hidden">
    <ChatHeader
      :active-chat="activeChat"
      :all-chats="allChats"
      :active-sources="activeSources()"
      :total-sources="sources.length"
      :exporting-chat="exportingChat"
      @select-chat="handleSelectChat"
      @new-chat="handleNewChat"
      @show-chat-list="showChatList = true"
      @export-chat="handleExportChat"
    />

    <ChatMessages
      :messages="activeChat?.messages || []"
      :sending="sending"
      :project-id="props.projectId"
    />

    <ChatInput
      :message="message"
      :partial-transcript="partialTranscript"
      :is-recording="isRecording"
      :sending="sending"
      :transcription-configured="transcriptionConfigured"
      @update:message="message = $event"
      @send="handleSend"
      @mic-click="handleMicClick"
    />
  </div>
</template>
