// frontend/src/components/project/ProjectList.vue
<script setup lang="ts">
/**
 * ProjectList Component
 * Educational Note: Data fetching with onMounted + watch pattern.
 * - `watch(refreshTrigger, loadProjects)` replaces `useEffect([refreshTrigger])`
 * - `onMounted(loadProjects)` replaces `useEffect([], loadProjects)` (initial fetch)
 */
import { ref, watch, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { PhPlus, PhTrash, PhClock, PhPencilSimple } from '@phosphor-icons/vue'
import { Button } from '@/components/ui/button'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import CreateProjectDialog from '@/components/dashboard/CreateProjectDialog.vue'
import { projectsAPI } from '@/lib/api'
import { createLogger } from '@/lib/logger'

const log = createLogger('project-list')

interface Project {
  id: string
  name: string
  description: string
  created_at: string
  updated_at: string
  last_accessed: string
}

const props = withDefaults(defineProps<{
  refreshTrigger?: number
}>(), {
  refreshTrigger: 0,
})

const emit = defineEmits<{
  createNew: []
}>()

const router = useRouter()

const projects = ref<Project[]>([])
const loading = ref(true)
const loadError = ref<string | null>(null)
const deleteDialogOpen = ref(false)
const projectToDelete = ref<string | null>(null)
const editProject = ref<{ id: string; name: string; description: string } | null>(null)

async function loadProjects() {
  try {
    loading.value = true
    loadError.value = null
    const response = await projectsAPI.list()
    projects.value = response.data.projects || []
  } catch (err) {
    loadError.value = 'Failed to load projects'
    log.error({ err }, 'failed to load projects')
  } finally {
    loading.value = false
  }
}

onMounted(loadProjects)

// Re-fetch when parent increments refreshTrigger
watch(() => props.refreshTrigger, loadProjects)

async function handleOpenProject(project: Project) {
  try {
    await projectsAPI.open(project.id)
    router.push(`/projects/${project.id}`)
  } catch (err) {
    log.error({ err }, 'failed to open project')
  }
}

function handleDeleteClick(e: MouseEvent, projectId: string) {
  e.stopPropagation()
  projectToDelete.value = projectId
  deleteDialogOpen.value = true
}

async function handleConfirmDelete() {
  if (!projectToDelete.value) return
  try {
    await projectsAPI.delete(projectToDelete.value)
    await loadProjects()
  } catch (err) {
    log.error({ err }, 'failed to delete project')
  } finally {
    deleteDialogOpen.value = false
    projectToDelete.value = null
  }
}

function formatDate(dateString: string): string {
  return new Date(dateString).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  })
}
</script>

<template>
  <!-- Loading -->
  <div v-if="loading" class="flex items-center justify-center h-screen">
    <div class="text-center">
      <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-primary mx-auto" />
      <p class="mt-4 text-muted-foreground">Loading projects...</p>
    </div>
  </div>

  <!-- Error -->
  <div v-else-if="loadError" class="flex items-center justify-center h-screen">
    <div class="text-center">
      <p class="text-destructive mb-4">{{ loadError }}</p>
      <Button @click="loadProjects">Try Again</Button>
    </div>
  </div>

  <!-- Project grid -->
  <div v-else class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
    <!-- Create New Project Card -->
    <Card
      class="cursor-pointer bg-[#e8e7e4] hover:bg-[#dddcd8] border-transparent transition-colors"
      @click="emit('createNew')"
    >
      <CardContent class="flex flex-col items-center justify-center h-full min-h-[140px] py-8">
        <div class="w-14 h-14 rounded-full bg-primary/10 flex items-center justify-center mb-3">
          <PhPlus :size="28" weight="bold" class="text-primary" />
        </div>
        <p class="font-semibold text-base">Create New Project</p>
      </CardContent>
    </Card>

    <!-- Existing Projects -->
    <Card
      v-for="project in projects"
      :key="project.id"
      class="cursor-pointer hover:bg-stone-50 transition-colors"
      @click="handleOpenProject(project)"
    >
      <CardHeader>
        <div class="flex justify-between items-start">
          <div class="flex-1">
            <CardTitle class="text-lg">{{ project.name }}</CardTitle>
            <CardDescription class="mt-1">
              {{ project.description || 'No description' }}
            </CardDescription>
          </div>
          <div class="flex items-center gap-1 ml-2">
            <Button
              variant="ghost"
              size="icon"
              @click.stop="editProject = { id: project.id, name: project.name, description: project.description }"
            >
              <PhPencilSimple :size="20" weight="bold" />
            </Button>
            <Button
              variant="ghost"
              size="icon"
              @click.stop="(e: MouseEvent) => handleDeleteClick(e, project.id)"
            >
              <PhTrash :size="20" weight="bold" />
            </Button>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        <div class="flex items-center text-sm text-muted-foreground">
          <PhClock :size="16" weight="bold" class="mr-1" />
          Last opened: {{ formatDate(project.last_accessed) }}
        </div>
      </CardContent>
    </Card>
  </div>

  <!-- Delete Confirmation Dialog -->
  <Dialog :open="deleteDialogOpen" @update:open="deleteDialogOpen = $event">
    <DialogContent>
      <DialogHeader>
        <DialogTitle>Delete Project</DialogTitle>
        <DialogDescription>
          Are you sure you want to delete this project? This action cannot be undone.
          All sources, chats, and data will be permanently deleted.
        </DialogDescription>
      </DialogHeader>
      <DialogFooter>
        <Button variant="soft" @click="deleteDialogOpen = false">Cancel</Button>
        <Button variant="destructive" @click="handleConfirmDelete">Delete</Button>
      </DialogFooter>
    </DialogContent>
  </Dialog>

  <!-- Edit Project Dialog -->
  <CreateProjectDialog
    v-if="editProject"
    :edit-project="editProject"
    @close="editProject = null"
    @project-created="() => { editProject = null; loadProjects() }"
  />
</template>

// frontend/src/components/project/ProjectList.tsx
import React, { useState, useEffect, useMemo } from 'react';
import { Plus, Trash, Clock, PencilSimple } from '@phosphor-icons/react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../ui/card';
import { Button } from '../ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '../ui/dialog';
import { projectsAPI } from '@/lib/api';
import { CreateProjectDialog } from '@/components/dashboard/CreateProjectDialog';
import { createLogger } from '@/lib/logger';

const log = createLogger('project-list');

/**
 * ProjectList Component
 * Educational Note: This component displays all projects and handles
 * project selection. It demonstrates React hooks (useState, useEffect)
 * and async data fetching patterns.
 */

interface Project {
  id: string;
  name: string;
  description: string;
  created_at: string;
  updated_at: string;
  last_accessed: string;
}

interface ProjectListProps {
  onSelectProject: (project: Project) => void;
  onCreateNew: () => void;
  refreshTrigger?: number; // Used to refresh the list when projects change
}

export const ProjectList: React.FC<ProjectListProps> = ({
  onSelectProject,
  onCreateNew,
  refreshTrigger = 0
}) => {
  const [projects, setProjects] = useState<Project[]>([]);

  // Sort by most-recently-opened so the project a user usually returns to
  // floats to the top. Falls back to updated_at and finally created_at if
  // last_accessed isn't populated yet (older rows from before that column
  // was added). Projects whose timestamps are missing land at the bottom.
  const sortedProjects = useMemo(() => {
    const tsOf = (p: Project) => {
      const t = p.last_accessed || p.updated_at || p.created_at;
      const ms = t ? Date.parse(t) : 0;
      return Number.isNaN(ms) ? 0 : ms;
    };
    return [...projects].sort((a, b) => tsOf(b) - tsOf(a));
  }, [projects]);
  const [loading, setLoading] = useState(true);
  // Switches the loading caption from "Loading projects..." to "Reconnecting…"
  // after 3s. The api-client interceptor silently retries transient GET
  // failures (network / 502 / 503 / 504) up to 3 times at 1s/2s/4s — so a
  // deploy cutover stretches this load to ~7s and "Reconnecting…" tells the
  // user we know about it instead of showing nothing then a red error.
  const [reconnecting, setReconnecting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
  const [projectToDelete, setProjectToDelete] = useState<string | null>(null);
  const [editProject, setEditProject] = useState<{ id: string; name: string; description: string } | null>(null);

  // Fetch projects from API
  useEffect(() => {
    loadProjects();
  }, [refreshTrigger]); // Re-fetch when refreshTrigger changes

  const loadProjects = async () => {
    let reconnectTimer: ReturnType<typeof setTimeout> | null = null;
    try {
      setLoading(true);
      setError(null);
      setReconnecting(false);
      reconnectTimer = setTimeout(() => setReconnecting(true), 3000);
      const response = await projectsAPI.list();
      setProjects(response.data.projects || []);
    } catch (err) {
      setError('Failed to load projects');
      log.error({ err }, 'failed to load projects');
    } finally {
      if (reconnectTimer) clearTimeout(reconnectTimer);
      setReconnecting(false);
      setLoading(false);
    }
  };

  const handleOpenProject = async (project: Project) => {
    try {
      // Mark project as opened
      await projectsAPI.open(project.id);
      // Select the project
      onSelectProject(project);
    } catch (err) {
      log.error({ err }, 'failed to open project');
    }
  };

  const handleDeleteClick = (e: React.MouseEvent, projectId: string) => {
    e.stopPropagation(); // Prevent card click
    setProjectToDelete(projectId);
    setDeleteDialogOpen(true);
  };

  const handleConfirmDelete = async () => {
    if (!projectToDelete) return;

    try {
      await projectsAPI.delete(projectToDelete);
      loadProjects(); // Refresh the list
    } catch (err) {
      log.error({ err }, 'failed to delete project');
    } finally {
      setDeleteDialogOpen(false);
      setProjectToDelete(null);
    }
  };

  const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-screen">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary mx-auto"></div>
          <p className="mt-4 text-muted-foreground">
            {reconnecting ? 'Reconnecting…' : 'Loading projects...'}
          </p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex items-center justify-center h-screen">
        <div className="text-center">
          <p className="text-destructive mb-4">{error}</p>
          <Button onClick={loadProjects}>Try Again</Button>
        </div>
      </div>
    );
  }

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
      {/* Create New Project Card - Always first */}
      <Card
        className="cursor-pointer bg-[#e8e7e4] hover:bg-[#dddcd8] border-transparent transition-colors"
        onClick={onCreateNew}
      >
        <CardContent className="flex flex-col items-center justify-center h-full min-h-[140px] py-8">
          <div className="w-14 h-14 rounded-full bg-primary/10 flex items-center justify-center mb-3">
            <Plus size={28} weight="bold" className="text-primary" />
          </div>
          <p className="font-semibold text-base">Create New Project</p>
        </CardContent>
      </Card>

      {/* Existing Projects, most-recently-opened first */}
      {sortedProjects.map((project) => (
        <Card
          key={project.id}
          className="cursor-pointer hover:bg-stone-50 transition-colors"
          onClick={() => handleOpenProject(project)}
        >
          <CardHeader>
            <div className="flex justify-between items-start">
              <div className="flex-1">
                <CardTitle className="text-lg">{project.name}</CardTitle>
                <CardDescription className="mt-1">
                  {project.description || 'No description'}
                </CardDescription>
              </div>
              <div className="flex items-center gap-1 ml-2">
                <Button
                  variant="ghost"
                  size="icon"
                  onClick={(e) => {
                    e.stopPropagation();
                    setEditProject({ id: project.id, name: project.name, description: project.description });
                  }}
                >
                  <PencilSimple size={20} weight="bold" />
                </Button>
                <Button
                  variant="ghost"
                  size="icon"
                  onClick={(e) => handleDeleteClick(e, project.id)}
                >
                  <Trash size={20} weight="bold" />
                </Button>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <div className="flex items-center text-sm text-muted-foreground">
              <Clock size={16} weight="bold" className="mr-1" />
              Last opened: {formatDate(project.last_accessed)}
            </div>
          </CardContent>
        </Card>
      ))}

      {/* Delete Confirmation Dialog */}
      <Dialog open={deleteDialogOpen} onOpenChange={setDeleteDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Delete Project</DialogTitle>
            <DialogDescription>
              Are you sure you want to delete this project? This action cannot be undone.
              All sources, chats, and data will be permanently deleted.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button variant="soft" onClick={() => setDeleteDialogOpen(false)}>
              Cancel
            </Button>
            <Button
              variant="destructive"
              onClick={handleConfirmDelete}
            >
              Delete
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Edit Project Dialog */}
      {editProject && (
        <CreateProjectDialog
          editProject={editProject}
          onClose={() => setEditProject(null)}
          onProjectCreated={() => {
            setEditProject(null);
            loadProjects();
          }}
        />
      )}
    </div>
  );
};
